package fr.artemis.phone.webservices;

public enum WsName {

	// Authentification
	AUTHENTIFICATION,

	// Equipements
	DELETE_EQUIPEMENT,
	DELETE_EQUIPEMENT_SALARIE,
	GENERATE_EMPTY_EQUIPEMENT,
	GENERATE_EMPTY_EQUIPEMENT_SALARIE,
	GET_LISTE_EQUIPEMENTS,
	GET_LISTE_EQUIPEMENTS_SALARIE,
	GET_LISTE_EQUIPEMENTS_SALARIE_ACTIVES,
	GET_LISTE_EQUIPEMENTS_SALARIE_POSSEDES,
	GET_LISTE_TYPE_TAILLES,
	IS_EQUIPEMENT_DELETABLE,
	IS_EQUIPEMENT_SALARIE_DELETABLE,
	SAVE_EQUIPEMENT,
	SAVE_EQUIPEMENT_SALARIE,

	// Decheteries
	GET_DECHETERIES_UPDATES,
	GET_KML_DECHETERIE,
	GET_VERSION_MAP_DECHETERIE,
	UPDATE_DECHETERIE,

	// Dépots vente
	GET_KML_DEPOTS_VENTE,
	GET_LISTE_DEPOTS_VENTE,
	GET_VERSION_MAP_DEPOTS_VENTE,
	UPDATE_DEPOT_VENTE,

	// Documents
	GET_DOCUMENTS,
	SEND_DOCUMENT,

	// Horaires
	GET_BALANCE_TOTALE_HORAIRE,
	GET_LISTE_HORAIRES_BY_ID_USER,
	UPDATE_HORAIRE,

	// Planning
	GET_DEVIS_FILE,
	GET_PLANNING_SEMAINE,
	GET_LISTE_PLANNINGS_BETWEEN,
	GET_LISTE_PLANNINGS_INTERVENTION_BETWEEN,

	// Rapports
	GET_INTERVENTION_DETAIL_BY_ID_DEVIS,
	GET_RAPPORT_CHANTIER,
	GET_LISTE_RAPPORTS_CHANTIER_PLANNING,
	SAVE_RAPPORT_CHANTIER,
	UPLOAD_PHOTO,

	// Salarié
	GET_LISTE_SALARIES_ACTIFS,
	GET_SALARIE_BY_ID_USER
}