package fr.artemis.phone.fragments;

public enum FragmentTags {

	ACCUEIL_RESPONSABLE( "ACCUEIL_RESPONSABLE" ),

	ACCUEIL_UTILISATEUR( "ACCUEIL_UTILISATEUR" ),

	DECHETERIES( "DECHETERIES" ),

	DEPOTS_VENTE( "DEPOTS_VENTE" ),

	DOCUMENTS( "DOCUMENTS" ),

	EQUIPEMENTS_RESP_ACCUEIL( "EQUIPEMENTS_RESP_ACCUEIL" ),
	EQUIPEMENTS_RESP_DEMANDES( "EQUIPEMENTS_RESP_DEMANDES" ),
	EQUIPEMENTS_RESP_LISTE( "EQUIPEMENTS_RESP_LISTE" ),
	EQUIPEMENTS_RESP_SUIVI( "EQUIPEMENTS_RESP_SUIVI" ),
	EQUIPEMENTS_USER( "EQUIPEMENTS_USER" ),

	HORAIRES_USER( "HORAIRES_USER" ),

	LOGIN( "LOGIN" ),

	PLANNING_ACCUEIL( "PLANNING_ACCUEIL" ),
	PLANNING_SEMAINE( "PLANNING_SEMAINE" ),
	PLANNING_SYNCHRONISE( "PLANNING_SYNCHRONISE" ),

	RAPPORT_RESP( "RAPPORT_RESP" ),
	RAPPORT_RESP_GLOBAL( "RAPPORT_RESP_GLOBAL" ),
	RAPPORT_RESP_INCOHERENCE( "RAPPORT_RESP_INCOHERENCE" ),
	RAPPORT_RESP_INTERVENTION( "RAPPORT_RESP_INTERVENTION" ),
	RAPPORT_RESP_SALARIE( "RAPPORT_RESP_SALARIE" ),

	RAPPORT_CHANTIER( "RAPPORT_CHANTIER" ),
	SELECTION_RAPPORT_CHANTIER( "SELECTION_RAPPORT_CHANTIER" );

	private String tagName;

	FragmentTags( String tagName ) {
		this.tagName = tagName;
	}

	public String getTagName() {
		return tagName;
	}
}